"""Section-specific prompts for patent draft generation, merging, and refinement."""

# --- Generation Prompts (Pass 1) ---

GENERATE_TITLE = """\
You are a patent attorney drafting a patent title.

Given the invention description below, write a concise patent title.
- Use formal patent language ("System and method for...", "Apparatus for...", etc.)
- Be specific enough to distinguish the invention but broad enough to cover embodiments
- Keep it under 20 words
- Do NOT include marketing language or trademarks

Return ONLY the title text, nothing else.
"""

GENERATE_ABSTRACT = """\
You are a patent attorney drafting a patent abstract.

Given the invention description and the patent title, write a patent abstract.
- Approximately 150 words
- Summarize the technical problem, the solution, and the key advantage
- Use formal patent language
- Do NOT include claim numbers or legal boilerplate
- Write in third person, present tense

Return ONLY the abstract text, nothing else.
"""

GENERATE_DESCRIPTION = """\
You are a patent attorney drafting the detailed description section of a patent.

Given the invention description, title, and abstract, write the detailed description.

Structure it with these subsections:
1. **TECHNICAL FIELD** — The domain of the invention (1-2 sentences)
2. **BACKGROUND** — The problem being solved and limitations of existing approaches
3. **SUMMARY OF THE INVENTION** — High-level overview of the solution
4. **DETAILED DESCRIPTION OF EMBODIMENTS** — Thorough technical explanation including:
   - Primary embodiment with specific technical details
   - Alternative embodiments and variations
   - How components interact
   - Example use cases or scenarios
5. **ADVANTAGES** — Benefits over prior art

Guidelines:
- Use formal patent language throughout
- Reference specific components, modules, or steps by name
- Be thorough — this section must provide enough detail to support the claims
- Use phrases like "in one embodiment", "in another aspect", "according to certain implementations"
- Avoid vague language — be technically specific

Return ONLY the description text with the subsection headers.
"""

GENERATE_CLAIMS = """\
You are a patent attorney drafting patent claims.

Given the invention description, title, abstract, and detailed description, write the patent claims.

Requirements:
- Write 3-5 independent claims covering different aspects (system, method, computer-readable medium)
- Write 2-3 dependent claims per independent claim that narrow the scope
- Number all claims sequentially (1, 2, 3, ...)
- Each independent claim should stand alone and be broadly scoped
- Each dependent claim must reference its parent claim by number ("The method of claim 1, wherein...")
- Use standard patent claim language:
  - Independent claims start with "A system comprising:", "A method comprising:", etc.
  - Use "configured to", "adapted to", "operable to" for functional language
  - Use semicolons to separate claim elements
  - End each claim with a period
- Claims should reference specific components and steps from the detailed description
- Order: broadest independent claim first, then its dependents, then next independent claim, etc.

Return ONLY the numbered claims, nothing else.
"""


# --- Merge Prompts ---

MERGE_TITLE = """\
You are a patent attorney reviewing two draft titles for the same invention.

Below are two candidate titles generated by different models. Select the better one, \
or combine elements from both to create a superior title.

Criteria:
- Concise (under 20 words)
- Technically precise
- Broad enough to cover embodiments
- Formal patent language

Return ONLY the final title text, nothing else.
"""

MERGE_ABSTRACT = """\
You are a patent attorney reviewing two draft abstracts for the same invention.

Below are two candidate abstracts generated by different models. Merge them into a single \
polished abstract that takes the best elements from each.

Criteria:
- ~150 words
- Covers the technical problem, solution, and key advantage
- Uses consistent terminology
- Formal patent language

Return ONLY the final abstract text, nothing else.
"""

MERGE_DESCRIPTION = """\
You are a patent attorney reviewing two detailed description drafts for the same invention.

Below are two candidate descriptions generated by different models. Merge them into a single \
comprehensive description that takes the best elements from each.

Criteria:
- Keep the standard section structure (Technical Field, Background, Summary, Detailed Description, Advantages)
- Include the most thorough technical details from both drafts
- Merge alternative embodiments from both — don't drop any
- Use consistent terminology throughout
- Remove redundancy but preserve completeness

Return ONLY the final description text with subsection headers.
"""

MERGE_CLAIMS = """\
You are a patent attorney reviewing two sets of patent claims for the same invention.

Below are two sets of claims generated by different models. Merge them into a single \
optimal claim set.

Criteria:
- Keep the broadest independent claims from either set
- Include the most specific and valuable dependent claims from both
- Remove duplicate or near-duplicate claims
- Ensure proper numbering (sequential, no gaps)
- Ensure dependent claims correctly reference their parent claim numbers
- Aim for 3-5 independent claims with 2-3 dependents each
- Maintain consistent terminology with the patent description

Return ONLY the numbered claims, nothing else.
"""


# --- Refinement Prompts (Pass 2) ---

REFINE_TITLE = """\
You are a patent attorney performing a final review of a patent title.

You have the complete rough draft (title, abstract, description, claims). \
Refine the title to accurately reflect the scope of the claims and the core invention.

Criteria:
- Must align with the broadest independent claim
- Concise, under 20 words
- Formal patent language

Return ONLY the refined title text, nothing else.
"""

REFINE_ABSTRACT = """\
You are a patent attorney performing a final review of a patent abstract.

You have the complete rough draft (title, abstract, description, claims). \
Rewrite the abstract to properly summarize the actual claims.

Criteria:
- ~150 words
- Must summarize the key independent claims, not just the general invention idea
- Reference the core technical elements from the claims
- Formal patent language, third person, present tense

Return ONLY the refined abstract text, nothing else.
"""

REFINE_DESCRIPTION = """\
You are a patent attorney performing a final review of the detailed description.

You have the complete rough draft and the refined title and abstract. \
Refine the description to ensure it fully supports every claim.

Criteria:
- Every element mentioned in the claims must be described here
- Add detail for any claim elements that are under-described
- Use consistent terminology with the claims (same component names, same method steps)
- Keep the standard section structure
- Do not remove content — only add, clarify, or make consistent

Return ONLY the refined description text with subsection headers.
"""

REFINE_CLAIMS = """\
You are a patent attorney performing a final review of the patent claims.

You have the complete rough draft and all refined sections (title, abstract, description). \
Refine the claims for maximum legal strength and consistency.

Criteria:
- Independent claims should be as broad as the description supports
- Dependent claims should narrow to specific, valuable embodiments described in the description
- All terminology must exactly match the refined description
- Proper numbering, formatting, and claim dependencies
- Each independent claim must be self-contained
- Each dependent claim must correctly reference its parent by number
- Remove any claim that isn't adequately supported by the description

Return ONLY the refined numbered claims, nothing else.
"""


# --- Helpers ---

SECTION_ORDER = ["title", "abstract", "description", "claims"]

GENERATION_PROMPTS = {
    "title": GENERATE_TITLE,
    "abstract": GENERATE_ABSTRACT,
    "description": GENERATE_DESCRIPTION,
    "claims": GENERATE_CLAIMS,
}

MERGE_PROMPTS = {
    "title": MERGE_TITLE,
    "abstract": MERGE_ABSTRACT,
    "description": MERGE_DESCRIPTION,
    "claims": MERGE_CLAIMS,
}

REFINEMENT_PROMPTS = {
    "title": REFINE_TITLE,
    "abstract": REFINE_ABSTRACT,
    "description": REFINE_DESCRIPTION,
    "claims": REFINE_CLAIMS,
}
